### ISSUE TITLE
invalid float value in saveNewDataPoint function

### ISSUE THREAD

**Issue by do3meli** [do3meli/piLogger-cloud-functions#1]
the apache error log on the rest api shows the following error that seems to be causing apache to crash from time to time: 

```
[Tue Aug 11 23:10:26.756954 2015] [core:notice] [pid 1101] AH00094: Command line: '/usr/sbin/apache2'
exception 'Cassandra\Exception\InvalidArgumentException' with message 'Invalid float value: ''' in /home/ubuntu/piLogger-cloud-rest/vendor/do3meli/pilogger-cloud-functions/src/piCloudFunctions/piCloudHandler.php:29
Stack trace:
#0 /home/ubuntu/piLogger-cloud-rest/vendor/do3meli/pilogger-cloud-functions/src/piCloudFunctions/piCloudHandler.php(29): Cassandra\Float->__construct('')
#1 /home/ubuntu/piLogger-cloud-rest/src/index.php(54): piCloudFunctions\piCloudHandler->saveNewDataPoint('7435928de519d34...', 1439186411, '')
#2 [internal function]: {closure}('7435928de519d34...')
#3 /home/ubuntu/piLogger-cloud-rest/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#4 /home/ubuntu/piLogger-cloud-rest/vendor/slim/slim/Slim/Slim.php(1357): Slim\Route->dispatch()
#5 /home/ubuntu/piLogger-cloud-rest/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#6 /home/ubuntu/piLogger-cloud-rest/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#7 /home/ubuntu/piLogger-cloud-rest/vendor/dogancelik/slim-json/SlimJson/Middleware.php(128): Slim\Middleware\MethodOverride->call()
#8 /home/ubuntu/piLogger-cloud-rest/vendor/slim/slim/Slim/Slim.php(1302): SlimJson\Middleware->call()
#9 /home/ubuntu/piLogger-cloud-rest/src/index.php(151): Slim\Slim->run()
#10 {main}
```

the corresponding line 29 of the mentioned file is in the `saveNewDataPoint()` function and is create the Cassandra Float object: ` $value = new \Cassandra\Float($probeValue);`

**Comment by do3meli** [comment]
since using a newer version of php-driver from datastax it seems that this issue is gone now.
